package com.example.myapplication

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val home: String,
    val schedule: String,
    val talents: String,
    val merch: String,
    val settings: String,
    val language: String,
    val notifications: String,
    val darkMode: String,
    val liveNow: String,
    val otherLive: String,
    val latestNews: String,
    val today: String,
    val soon: String,
    val archive: String,
    val searchOshi: String,
    val notificationHistory: String,
    val back: String,
    val refresh: String,
    val notificationSound: String,
    val alerts: String,
    val liveNotifications: String,
    val selectLanguage: String,
    val cancel: String,
    val systemSettings: String,
    val defaultSound: String,
    val all: String,
    val liveStream: String,
    val clip: String,
    val shorts: String,
    val noLiveNow: String,
    val noScheduleToday: String,
    val noScheduleSoon: String,
    val noScheduleArchive: String,
    val memberLive: String,
    val liveNotification: String,
    val aboutApp: String
)

val ThaiStrings = AppStrings(
    home = "หน้าหลัก",
    schedule = "ตารางไลฟ์",
    talents = "ข้อมูลเมม",
    merch = "สินค้า",
    settings = "ตั้งค่า",
    language = "ภาษา",
    notifications = "การแจ้งเตือน",
    darkMode = "Dark Mode",
    liveNow = "กำลังไลฟ์อยู่",
    otherLive = "ไลฟ์อื่นๆ",
    latestNews = "ข่าวล่าสุด",
    today = "วันนี้",
    soon = "เร็วๆ นี้",
    archive = "จบไปแล้ว",
    searchOshi = "ค้นหาโอชิของคุณ...",
    notificationHistory = "ประวัติการแจ้งเตือน",
    back = "กลับ",
    refresh = "รีเฟรช",
    notificationSound = "เสียงเตือนที่ตั้งไว้",
    alerts = "การแจ้งเตือน (ระบบ)",
    liveNotifications = "การแจ้งเตือนสด",
    selectLanguage = "เลือกภาษา",
    cancel = "ยกเลิก",
    systemSettings = "ตั้งค่าในระบบ",
    defaultSound = "ค่าเริ่มต้น",
    all = "ทั้งหมด",
    liveStream = "สตรีมสด",
    clip = "คลิป",
    shorts = "Reel",
    noLiveNow = "ไม่มีใครกำลังไลฟ์ในขณะนี้",
    noScheduleToday = "ไม่มีรายการในวันนี้",
    noScheduleSoon = "ไม่มีรายการเร็วๆ นี้",
    noScheduleArchive = "ไม่พบรายการที่จบไปแล้ว",
    memberLive = "เมมเบอร์ที่คุณติดตามกำลังไลฟ์อยู่!",
    liveNotification = "แจ้งเตือนเมื่อเริ่มไลฟ์",
    aboutApp = "เกี่ยวกับแอป"
)

val EnglishStrings = AppStrings(
    home = "Home",
    schedule = "Schedule",
    talents = "Talents",
    merch = "Merch",
    settings = "Settings",
    language = "Language",
    notifications = "Notifications",
    darkMode = "Dark Mode",
    liveNow = "Live Now",
    otherLive = "Other Live",
    latestNews = "Latest News",
    today = "Today",
    soon = "Soon",
    archive = "Archive",
    searchOshi = "Search your Oshi...",
    notificationHistory = "Notification History",
    back = "Back",
    refresh = "Refresh",
    notificationSound = "Notification Sound",
    alerts = "Alerts (System)",
    liveNotifications = "Live Notifications",
    selectLanguage = "Select Language",
    cancel = "Cancel",
    systemSettings = "System Settings",
    defaultSound = "Default",
    all = "All",
    liveStream = "Live",
    clip = "Clip",
    shorts = "Reel",
    noLiveNow = "No one is live right now",
    noScheduleToday = "No schedule for today",
    noScheduleSoon = "No schedule soon",
    noScheduleArchive = "No archives found",
    memberLive = "A member you follow is live right now!",
    liveNotification = "Live Notifications",
    aboutApp = "About App"
)

val LocalStrings = compositionLocalOf { ThaiStrings }
